/**
 * The exported tables are the running game, not a memory of it.
 *
 * Three copies of the roster exist: this client's, the API's `content.json`
 * (which decides whether a saved deck is legal) and the game server's
 * `rules.json` and `species.json` (which decide what happens in a match). They
 * are generated by `npm run export:content` and they had been left behind.
 *
 * The client offered 151 cards; both servers knew 127. The 24 in between --
 * every Mega base form, Mewtwo, Rayquaza, Kyogre, Groudon, Zygarde -- could be
 * put in a deck, and then the API refused to save it and the server did not
 * know what had been played. The server's species table was further behind
 * still: 29 creatures missing and 22 entries stale, which quietly made the two
 * engines disagree about types.
 *
 * Nothing noticed, because nothing compared them. This is that comparison.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import * as cards from "../src/core/cards";
import { CARD_TABLE } from "../src/core/cardTable";
import speciesJson from "../src/data/species.json";
import typeChartJson from "../src/data/typeChart.json";

const read = (path: string) => JSON.parse(readFileSync(path, "utf8"));

const CONTENT = "../api/src/main/resources/content.json";
const RULES = "../server/src/main/resources/rules.json";
const SERVER_SPECIES = "../server/src/main/resources/species.json";
const SERVER_CHART = "../server/src/main/resources/typeChart.json";

describe("what was exported is what the game runs", () => {
  it("offers the API every card a deck may hold", () => {
    const exported = read(CONTENT).cards.map((c: { id: string }) => c.id);
    // Exactly, in order: a card the client offers and the API rejects is a
    // deck that cannot be saved, and one the API accepts and the client has
    // never heard of is a deck that cannot be drawn.
    expect(exported).toEqual(cards.ALL.map((c) => c.id));
  });

  it("tells the game server about every card that can reach the board", () => {
    // Wider than the deckable roster: evolutions and Mega forms are never
    // chosen and are certainly played.
    const exported = read(RULES).cards.map((c: { id: string }) => c.id);
    expect(exported).toEqual([...CARD_TABLE]);
  });

  it("hands the game server the same species table this client reads", () => {
    // Copied rather than derived, so this is the only thing standing between
    // the two engines and a silent disagreement about what a creature is.
    expect(read(SERVER_SPECIES)).toEqual(speciesJson);
  });

  it("hands the game server the same type chart", () => {
    expect(read(SERVER_CHART)).toEqual(typeChartJson);
  });
});
